title: Mohamed Abdallah
description: [Home](/index.md) [Research](/Research.md) [Publications](/Publications.md) [Research Team](/Team.md) [Teaching](/Teaching.md) [Professional Activities](/Activities.md)
theme: jekyll-theme-slate
