title: Mohamed Abdallah
email: moabdallah@hbku.edu.qa
description: > # this means to ignore newlines until "baseurl:"
  Academic Website

theme: jekyll-theme-slate
markdown: kramdown
theme: slate
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
